name: auto-run

on:
  push:
    paths:
      - algos/*.sh
    branches:
      - main
  workflow_dispatch:

jobs:
  list-algos:
    runs-on: ubuntu-22.04
    outputs:
      algo_list: ${{ steps.process_algos.outputs.algo_list }}
      runner: ${{ steps.select_runner.outputs.runner }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Find changed files
      if: ${{ github.event_name == 'push' }}
      id: find_changed_files
      uses: tj-actions/changed-files@v34
      with:
        files: 'algos/*.sh'
        json: 'true'

    - name: Process algorithms
      id: process_algos
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          algo_files=$(ls algos/*.sh | xargs -n1 basename)
        else
          algo_files=$(echo "${{ steps.find_changed_files.outputs.all_changed_files }}" | jq -r '.[]' | xargs -n1 basename)
        fi
        
        algo_list="["
        for file in $algo_files; do
          algo="${file%.sh}"
          autorun=$(jq -r ".${algo}.autoRun // .default.autoRun" .github/workflows/build-config.json)
          if [[ "$autorun" == "true" ]]; then
            algo_list+="\"$algo\","
          fi
        done
        algo_list=$(sed 's/,$/]/' <<< "$algo_list")
        
        echo "algo_list=${algo_list}"
        echo "algo_list=${algo_list}" >> $GITHUB_OUTPUT

    - name: Select runner
      id: select_runner
      run: |
        echo "runner=$( [ "${{ github.repository }}" == "QSMxT/QSM-CI" ] && echo "\"self-hosted\"" || echo "\"ubuntu-22.04\"" )"
        echo "runner=${runner}" >> $GITHUB_OUTPUT

  build-apps:
    needs: list-algos
    uses: ./.github/workflows/run-algos.yml
    with:
      algo_list: ${{ needs.list-algos.outputs.algo_list }}
      runner: ${{ needs.list-algos.outputs.runner }}
    secrets: inherit

    