name: Test
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_install:
    runs-on: "oracle-runner--${{ github.run_id }}"
    steps:
    - uses: actions/checkout@v3
    - name: Test test.sh
      env:
        RDM_USER: ${{ secrets.RDM_USER }}
        RDM_KEY: ${{ secrets.RDM_KEY }}
      run: |
        /bin/bash test.sh
        
