name: Reconstruct and evaluate
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'algos/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'algos/*.sh'
jobs:
  recon_and_evaluate:
    runs-on: "cirun-oracle--${{ github.run_id }}"
    steps:
    - uses: actions/checkout@v3
    - name: Get modified algorithms
      id: getfile
      run: |
        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^algos/.*\.sh$' | sed 's/^algos\///' | sed 's/\.sh$//')
        echo "Modified files: $FILES"
        echo "::set-output name=matrix::[\"$FILES\"]"
      shell: bash
    - name: Reconstruct and evaluate
      env:
        RDM_USER: ${{ secrets.RDM_USER }}
        RDM_KEY: ${{ secrets.RDM_KEY }}
      run: ./recon_and_eval.sh ${{fromJson(steps.getfile.outputs.matrix)}}
        
