name: Upload to object storage
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_install:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: upload
      env:
        RDM_USER: ${{ secrets.RDM_USER }}
        RDM_KEY: ${{ secrets.RDM_KEY }}
      run: |
        /bin/bash upload.sh
        
